In [45]:
import numpy as np
import pandas as pd

In [115]:
outflow = pd.read_csv('../../data/timeseries/Outflow.txt', sep=';', parse_dates=['Date'])
radiation = pd.read_csv('../../data/timeseries/Radiation.txt', sep=';', parse_dates=['time'])
SWC = pd.read_csv('../../data/timeseries/SWC.txt', sep=';', parse_dates=['time']) 
Tsoil = pd.read_csv('../../data/timeseries/Tsoil.txt', sep=';', parse_dates=['time'])
Wetter_Campbell = pd.read_csv('../../data/timeseries/Wetter_Campbell.txt', sep=';', parse_dates=['Date'])

In [117]:
for name, df in [('outflow', outflow), ('radiation', radiation), ('SWC', SWC), ('Tsoil', Tsoil), ('Wetter_Campbell', Wetter_Campbell)]:
    dups = df[df.duplicated(keep=False)].sort_values(df.columns[0])
    print(f"=== {name}: {len(dups)} rows involved in duplication ({df.duplicated().sum()} would be dropped) ===")
    display(dups.head(2))

=== outflow: 0 rows involved in duplication (0 would be dropped) ===

Empty DataFrame
Columns: [Date, Kies_Efflux, Extensiv1_Efflux, Extensiv2_Efflux, Sumpf1_Efflux, Sumpf2_Efflux, Zeitlysi_Efflux.x, Sensorlysi_Efflux.x, Zeitlysi_Efflux.y, Sensorlysi_Efflux.y]
Index: []

=== radiation: 1752 rows involved in duplication (876 would be dropped) ===

,time,CNR4.1.1,CNR4.1.2,CNR4.1.3,CNR4.1.4,CNR4.1.T,CNR4.2.1,CNR4.2.2,CNR4.2.3,CNR4.2.4,...,KD.LWdown,KD.LWup,KD.TSFC,KD.TSFCkorr,SD.SWdown,SD.SWup,SD.LWdown,SD.LWup,SD.TSFC,SD.TSFCkorr
2399,2025-04-20 19:30:00,"0,0533333333333333","0,0566666666666667","-134,778146666667","-134,778413333333",0,"-0,0184","0,0137333333333333","-0,121133333333333","0,0370666666666667",...,"374,932958255165","385,632089707276","290,881851174413","287,280371493242","-1,35643156093438","0,2256394","374,932958255165","379,622424","289,741896488178","286,096646135705"
2400,2025-04-20 19:30:00,"0,0533333333333333","0,0566666666666667","-134,778146666667","-134,778413333333",0,"-0,0184","0,0137333333333333","-0,121133333333333","0,0370666666666667",...,"374,932958255165","385,632089707276","290,881851174413","287,280371493242","-1,35643156093438","0,2256394","374,932958255165","379,622424","289,741896488178","286,096646135705"

=== SWC: 1620 rows involved in duplication (810 would be dropped) ===

,time,QGravel,QEx1,QEx2,QIn,QWetland
13006,2025-04-20 23:00:00,"3,078","27,6766666666667","22,1623333333333","29,0853332888889","85,3881333333333"
13055,2025-04-20 23:00:00,"3,078","27,6766666666667","22,1623333333333","29,0853332888889","85,3881333333333"

=== Tsoil: 1590 rows involved in duplication (795 would be dropped) ===

,time,TGravel,TEx1,TEx2,TIn,TWetland
13009,2025-04-20 20:30:00,"15,3005334933333","16,4353335111111","16,0991669666667","12,1018888888889","16,3809334133333"
13058,2025-04-20 20:30:00,"15,3005334933333","16,4353335111111","16,0991669666667","12,1018888888889","16,3809334133333"

=== Wetter_Campbell: 0 rows involved in duplication (0 would be dropped) ===

Empty DataFrame
Columns: [Date, Tmean, Tmax, Rain, Rad_SW, RH, windspeed]
Index: []

In [118]:
outflow = outflow.drop_duplicates()
radiation = radiation.drop_duplicates()
SWC = SWC.drop_duplicates()
Tsoil = Tsoil.drop_duplicates()
Wetter_Campbell = Wetter_Campbell.drop_duplicates()
len(outflow), len(radiation), len(SWC), len(Tsoil), len(Wetter_Campbell)

(15867, 10276, 28693, 28729, 23103)